server:
    port: 8888
db:
    type: postgre
spring:
    datasource:
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        initialization-mode: always
        password: '!23dlatl'
        platform: postgres
        sql-script-encoding: utf-8
        url: jdbc:log4jdbc:postgresql://192.168.0.241:5432/sgsas
        username: sig_app
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
        show-sql: false
        
logging:
  level:
    com:
      sgva:
        rasa: debug
        
rasa:
  call:
    url: http://localhost:5005/
    msg: /webhooks/rest/webhook
#    url: "http://192.168.0.240:5005/"
  train:
    path:
      root: C:/train/
#      root: /usr/local/rasa/
#      root: /usr/local/volume/rasa/
  ## 순서가 있는거라 이 순서는 꼭 유지해야함
      file:
        config: config/config.yml
        nlu: data/nlu.yml
        stories: data/stories.yml 
        rules: data/rules.yml 
        domain: domain/domain.yml 
        responses: domain/responses.yml   
        forms: domain/forms.yml 

bert:
  train:
    path:
#      root: /usr/local/rasa/excel/
#      root: /usr/local/volume/bert/
      root: C:/Users/solugate/git/sgva-chatbot/bert_faq/excel/
      ## file path 로 수정 
#      _out : 메서드로 만들어진 파일이 나오는곳 , 파일명
#      bert_train : 훈련용 데이터 , bert_verify: 검증용 데이터
      file:
        faq_data : faq_data.xlsx
        faq_data_out : faq_dataOut.xlsx
        bert_train: train/bert_train.xlsx
        bert_train_out: train/bert_trainOut.xlsx
        bert_verify: train/bert_verify.xlsx
        bert_verify_out: train/bert_verifyOut.xlsx
        
        
 
 
    